2022-06-13

diff --git a/home/zsh/.config/zsh/functions/ytv b/home/zsh/.config/zsh/functions/ytv
--- a/home/zsh/.config/zsh/functions/ytv
+++ b/home/zsh/.config/zsh/functions/ytv
@@ -14,23 +14,32 @@ ytv() {
     # best_quality_format='bv*+ba/b'
 
     if [ "$#" -gt 0 ]; then
-        local __FORMAT='bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b'
-        local __OUTPUT="$HOME/Videos/youtube/processed/%(title)s.%(ext)s"
+        local __FORMAT='bv*+ba/b'
+        local __OUTPUT="$HOME/Videos/youtube/downloads/%(title)s.%(ext)s"
+        local __SORT_ORDER='res,vbr,asr,abr'
         local __CONFIG_PATH="$HOME/.config/yt-dlp/config"
         local __LOG_PATH="$HOME/.local/share/yt-dlp/logs/video"
         local __LOG_FILE="$__LOG_PATH/$(date +'%F--%T').log"
 
+        "$HOME/.config/zsh/functions/lib/__print_in_block"
+
         yt-dlp \
             --config-location "$__CONFIG_PATH" \
             --format "$__FORMAT" \
+            --format-sort "$__SORT_ORDER" \
             --output "$__OUTPUT" \
             "$@" 2> "$__LOG_FILE"
 
+        if (( $? != 0 )); then
+            echo -e "\n${RED}Failed to download video${NOCOLOR}"
+        else
+############## [[ $file == *.mp4 ]] ||
         "$ZCONFDIR/functions/lib/__remux_mp4" "$(dirname "$__OUTPUT")"
 
         printf \
-            "${c[green]}Successfully ${c[reset]} downloaded as ${c[light_blue]} %s. ${c[reset]}\n" \
+            "${LIGHTGREEN}Successfully ${NOCOLOR} downloaded as ${BLUE} %s. ${NOCOLOR}\n" \
             "$(/bin/ls -Art "$(dirname "$__OUTPUT")" | tail -n 1)"
+        fi
     else
         usage
     fi
